#################################################################
###################### Hexo Configuration #######################
#################################################################

# Site
title: 洽洽的博客
subtitle: ''
description: ''
keywords: "big data"
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://jinyaqia.github.io.com
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:
  - robots.txt
  - animate/*
  - highlight/*

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''


# Home page setting
index_generator:
  path: ''
  per_page: 20
  order_by: date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
per_page: 20
pagination_dir: page

# Extensions
theme: next

archive_generator:
  per_page: 20
  yearly: true
  monthly: true
  daily: false

category_generator:
  per_page: 20
  order_by: date
  category_generator: true

tag_generator:
  per_page: 20
  order_by: date
  tag_generator: true

marked:
  # For preserve original quotes in code blocks.
  smartypants: false
  lazyload: true

search:
  path: search.json
  field: all

# search:
#   path: search.xml
#   field: post

symbols_count_time:
  time: true                   # 文章阅读时长
  symbols: true                # 文章字数统计
  total_time: true             # 站点总阅读时长
  total_symbols: true          # 站点总字数统计
  exclude_codeblock: true      # 排除代码字数统计
  awl: 4
  wpm: 275
  suffix: "mins."


sitemap:
   path: sitemap.xml
   template: ./sitemap_template.xml

deploy:
  type: git
  repo: 	git@github.com:jinyaqia/jinyaqia.github.io.git
  branch: pages